package shazam.hash;

import com.sun.xml.internal.bind.v2.runtime.reflect.opt.Const;

import java.util.ArrayList;

/**
 * Created by Wen Ke on 2016/10/20.
 * Generating a constellation map for each audio.
 */
public class ConstellationMap {

    // What a terrible mistake !
    // dividing an int by an INT ?! Naive!
    public static final double scaling = FFT.WINDOW_SIZE / 44100.0;

    public static final int interval_num = 4;

    public static final int start_freq = 55; // The frequency of tone A1

    private static final int[][] freqRanges = new int[interval_num][2];

    static {
        for (int i = 0; i < interval_num; ++i) {
            freqRanges[i][0] = (int) Math.round((start_freq << i) * scaling);
            freqRanges[i][1] = (int) Math.round((start_freq << (i + 1)) * scaling);
        }
    }

    private ArrayList<int[]> constel_data = new ArrayList<>();
    private int id;

    /**
     * For songs about to add into DB
     * @param id
     */
    public ConstellationMap(int id) {
        this.id = id;
    }

    /**
     * For songs about to be searched
     */
    public ConstellationMap() {
        this.id = -1;
    }

    /**
     * Append a column of frequency peaks to the constellation map.
     * A frequency peak is a frequency value whose amplitude is the highest among
     * all frequencies in a frequency interval.
     *
     * @param freqDomain The frequency domain constel_data generated by FFT.
     */
    public void append(double[] freqDomain) {
        int[] freqPeaks = new int[interval_num];

        // The maximum amplitude and its frequency
        double max;
        int max_freq;

        // find the peak frequency in each interval
        for (int i = 0; i < interval_num; ++i) {
            max = 0;
            max_freq = freqRanges[i][0];
            for (int j = freqRanges[i][0]; j < freqRanges[i][1]; ++j) {
                if (freqDomain[j] > max) {
                    max = freqDomain[j];
                    max_freq = j;
                }
            }
            freqPeaks[i] = max_freq;
        }
        constel_data.add(freqPeaks);
    }

    /**
     * Generate fingerprints using Combinational Hash.
     * For each frequency peak, generate 8 fingerprints with its 8 successors.
     *
     * @return
     */
    public ArrayList<ShazamHash> shazamHash() {
        if (constel_data.size() < 3)
            throw new RuntimeException("Too few frequency peaks");
        ArrayList<ShazamHash> hashes = new ArrayList<>();
        for (int i = 0; i < constel_data.size() - 2; ++i) {
            for (int k = 0; k < interval_num; ++k) {
                for (int j = 1; j <= 2; ++j) {
                    for (int kk = 1; kk < interval_num; ++kk) {
                        ShazamHash hash = new ShazamHash();
                        hash.f1 = (short) constel_data.get(i)[k];
                        hash.f2 = (short) constel_data.get(i + j)[kk];
                        hash.dt = (short) j;
                        hash.offset = i;
                        hash.id = id;
                        hashes.add(hash);
                    }
                }
            }
        }
        return hashes;
    }
}
